// apps/pc/src/pages/Home/Chats/components/PendingSendBar.tsx
import { invoke } from '@tauri-apps/api/core';
import { useIntl } from '@umijs/max';
import {
  CloseOutlined,
  DownOutlined,
  LoadingOutlined,
  UpOutlined,
} from '@ant-design/icons';
import { ChatRecordSend } from '@workspace/types';
import { message } from 'antd';
import React, { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import resendSvg from '@/assets/svg/resend.svg';
import styles from './styles/PendingSendBar.less';

/** 默认/最小高度 */
export const PENDING_BAR_HEIGHT = 48;
/** 拖拽可展开的最大高度 */
export const PENDING_BAR_MAX_HEIGHT = 160;
/** 折叠后的窄条高度 */
export const PENDING_BAR_COLLAPSED_HEIGHT = 22;

interface PendingSendBarProps {
  friendUuid: string;
  /** 父页面自增信号，变化时重新拉取（201 ACK / 发送新消息后触发） */
  refreshSignal: number;
  /** 绝对定位：距父容器底部偏移（即 footer 高度），使待发送条悬浮在 footer 顶部、不挤压布局 */
  bottom?: number;
  /** 可见性变化通知（记录清空时父页面回收高度） */
  onVisibleChange: (visible: boolean) => void;
}

/** 将 send 表 raw 解析为可展示的摘要文本 */
const formatRaw = (record: ChatRecordSend): string => {
  try {
    switch (record.text_type) {
      case 1: {
        const parsed = JSON.parse(record.raw);
        return parsed.text ?? record.raw;
      }
      case 2:
        return '[图片]';
      case 3: {
        const parsed = JSON.parse(record.raw);
        return parsed.file_name ?? '[文件]';
      }
      default:
        return record.raw;
    }
  } catch {
    return record.raw;
  }
};

const PendingSendBar: React.FC<PendingSendBarProps> = ({
  friendUuid,
  refreshSignal,
  bottom = 0,
  onVisibleChange,
}) => {
  const intl = useIntl();
  const [pendingList, setPendingList] = useState<ChatRecordSend[]>([]);
  const [actingId, setActingId] = useState('');
  const [height, setHeight] = useState(PENDING_BAR_HEIGHT);
  const [collapsed, setCollapsed] = useState(false);
  const [dragging, setDragging] = useState(false);
  const dragStartRef = useRef({ y: 0, h: PENDING_BAR_HEIGHT });
  // 操作兜底计时器：invoke 异常挂起时强制解禁，避免按钮一直处于禁用状态
  const actingTimerRef = useRef<number>();

  // 统一的操作入口：置位 actingId → 执行 → 解禁；异常/超时兜底保证界面不卡死
  const runAction = useCallback(async (sendId: string, action: () => Promise<void>) => {
    setActingId(sendId);
    window.clearTimeout(actingTimerRef.current);
    // 兜底：15 秒后无论 invoke 是否返回都强制解禁（正常路径后端 10 秒锁超时会返回错误）
    actingTimerRef.current = window.setTimeout(() => {
      setActingId('');
    }, 15000);
    try {
      await action();
    } finally {
      window.clearTimeout(actingTimerRef.current);
      setActingId('');
    }
  }, []);

  useEffect(() => {
    return () => window.clearTimeout(actingTimerRef.current);
  }, []);

  const fetchList = useCallback(async (): Promise<ChatRecordSend[]> => {
    try {
      const list = await invoke<ChatRecordSend[]>('get_pending_send_records', {
        recvUser: friendUuid,
      });
      setPendingList(list);
      return list;
    } catch (e) {
      console.log('获取待发送记录失败', e);
      return [];
    }
  }, [friendUuid]);

  useEffect(() => {
    fetchList();
  }, [fetchList, refreshSignal]);

  // 队列未清空时每 1s 轮询一次，直到记录全部消失（发送完成/忽略/清空）
  useEffect(() => {
    if (pendingList.length === 0) return;
    const timer = setInterval(() => {
      fetchList();
    }, 1000);
    return () => clearInterval(timer);
  }, [pendingList.length, fetchList]);

  const sendingList = useMemo(
    () => pendingList.filter((r) => r.send_status === 0 || r.send_status === 1),
    [pendingList],
  );
  const failedList = useMemo(
    () => pendingList.filter((r) => r.send_status === 2),
    [pendingList],
  );

  // 可见性控制：避免对纯待发送列表过于敏感。
  // 只有待发送（排队/发送中）记录时，需等重试次数超过 1 次才显示；
  // 一旦出现明确失败记录则立即显示。
  const shouldShow = useMemo(() => {
    const hasFailed = failedList.length > 0;
    const hasRetriedSending = sendingList.some((r) => r.retry_count > 1);
    return hasFailed || hasRetriedSending;
  }, [sendingList, failedList]);

  useEffect(() => {
    onVisibleChange(shouldShow);
  }, [shouldShow, onVisibleChange]);

  // 绝对定位：悬浮在 footer 顶部，不参与文档流、不挤压布局
  const positionStyle: React.CSSProperties = {
    position: 'absolute',
    bottom,
    left: 0,
    right: 0,
    zIndex: 3,
  };

  // 顶部拖拽手柄：向上拖变高，向下拖变矮，window 级监听保证拖出组件也不断
  const handleDragStart = (e: React.PointerEvent<HTMLDivElement>) => {
    e.preventDefault();
    setDragging(true);
    dragStartRef.current = { y: e.clientY, h: height };
    const onMove = (ev: PointerEvent) => {
      const { y, h } = dragStartRef.current;
      const next = Math.max(
        PENDING_BAR_HEIGHT,
        Math.min(PENDING_BAR_MAX_HEIGHT, h + (y - ev.clientY)),
      );
      setHeight(next);
    };
    const onUp = () => {
      setDragging(false);
      window.removeEventListener('pointermove', onMove);
      window.removeEventListener('pointerup', onUp);
    };
    window.addEventListener('pointermove', onMove);
    window.addEventListener('pointerup', onUp);
  };

  if (!shouldShow) return null;

  // 折叠态：窄条 + 失败计数徽标，点击整条展开
  if (collapsed) {
    return (
      <div
        className={styles.collapsedBar}
        style={positionStyle}
        onClick={() => setCollapsed(false)}
        title={intl.formatMessage({ id: 'chat.pendingBar.expand' })}
      >
        <span className={styles.collapsedInfo}>
          <span className={styles.collapsedDot} />
          {intl.formatMessage({ id: 'chat.pendingBar.title' })}
          {failedList.length > 0 && (
            <span className={styles.collapsedBadge}>{failedList.length}</span>
          )}
        </span>
        <span className={styles.collapsedExpand}>
          <UpOutlined />
        </span>
      </div>
    );
  }

  const handleRetry = (sendId: string) =>
    runAction(sendId, async () => {
      try {
        await invoke('retry_send_msg', { sendId });
        const list = await fetchList();
        // 重发后仍处于失败态：网络不通，发送再次失败
        const stillFailed = list.some(
          (r) => r.send_id === sendId && r.send_status === 2,
        );
        if (stillFailed) {
          message.warning(intl.formatMessage({ id: 'chat.pendingBar.resendFailed' }));
        }
      } catch (e) {
        console.log(intl.formatMessage({ id: 'chat.pendingBar.resendFailed' }), e);
        message.error(intl.formatMessage({ id: 'chat.pendingBar.resendFailed' }));
        // 命令失败（如锁超时）也刷新一次，保证界面状态与后端一致
        await fetchList();
      }
    });

  const handleIgnore = (sendId: string) =>
    runAction(sendId, async () => {
      try {
        await invoke('ignore_send_msg', { sendId });
        await fetchList();
      } catch (e) {
        console.log(intl.formatMessage({ id: 'chat.pendingBar.ignoreFailed' }), e);
        message.error(intl.formatMessage({ id: 'chat.pendingBar.ignoreFailed' }));
      }
    });

  return (
    <div
      className={`${styles.pendingBar}${dragging ? ` ${styles.dragging}` : ''}`}
      style={{ ...positionStyle, height }}
    >
      <div className={styles.dragHandle} onPointerDown={handleDragStart} />
      <div className={`${styles.pane} ${styles.paneSending}`}>
        <div className={styles.paneTitle}>
          {intl.formatMessage({ id: 'chat.pendingBar.sending' })}
        </div>
        {sendingList.map((record) => (
          <div className={`${styles.item} ${styles.sendingItem}`} key={record.send_id}>
            {record.send_status === 1 ? (
              <LoadingOutlined className={styles.itemIcon} />
            ) : (
              <span className={styles.queuedLabel}>
                {intl.formatMessage({ id: 'chat.pendingBar.queued' })}
              </span>
            )}
            <span className={styles.itemText} title={formatRaw(record)}>
              {formatRaw(record)}
            </span>
          </div>
        ))}
      </div>
      <div className={`${styles.pane} ${styles.paneFailed}`}>
        <div className={styles.paneTitle}>
          {intl.formatMessage({ id: 'chat.pendingBar.failed' })}
        </div>
        {failedList.map((record) => {
          const isActing = actingId === record.send_id;
          return (
            <div
              className={`${styles.item} ${styles.failedItem}${isActing ? ` ${styles.actingItem}` : ''}`}
              key={record.send_id}
            >
              <span className={styles.itemText} title={formatRaw(record)}>
                {formatRaw(record)}
              </span>
              <button
                className={`${styles.actionBtn} ${styles.resendBtn}`}
                title={intl.formatMessage({ id: 'chat.pendingBar.resend' })}
                disabled={isActing}
                onClick={() => handleRetry(record.send_id)}
              >
                {isActing ? (
                  <LoadingOutlined className={styles.actionIcon} />
                ) : (
                  <img src={resendSvg} alt="resend" className={styles.actionIcon} />
                )}
              </button>
              <button
                className={`${styles.actionBtn} ${styles.ignoreBtn}`}
                title={intl.formatMessage({ id: 'chat.pendingBar.ignore' })}
                disabled={isActing}
                onClick={() => handleIgnore(record.send_id)}
              >
                <CloseOutlined className={styles.actionIcon} />
              </button>
            </div>
          );
        })}
      </div>
      <button
        className={styles.collapseBtn}
        title={intl.formatMessage({ id: 'chat.pendingBar.collapse' })}
        onClick={() => setCollapsed(true)}
      >
        <DownOutlined className={styles.collapseIcon} />
      </button>
    </div>
  );
};

export default React.memo(PendingSendBar);

// apps/mobile/src/components/chat/PendingSendBar.vue
<script setup lang="ts">
import { ref, computed, onMounted, onUnmounted, watch } from "vue";
import { invoke } from "@tauri-apps/api/core";
import { showToast } from "vant";
import type { ChatRecordSend } from "@workspace/types";

const props = defineProps<{
  friendUuid: string;
  /** 父页面自增信号，变化时重新拉取（发送新消息 / 201/202 ACK 后触发） */
  refreshSignal: number;
}>();

const pendingList = ref<ChatRecordSend[]>([]);
const actingId = ref("");
const collapsed = ref(false);
let actingTimer: ReturnType<typeof setTimeout> | undefined;
let pollTimer: ReturnType<typeof setInterval> | undefined;

/** 将 send 表 raw 解析为可展示的摘要文本 */
const formatRaw = (record: ChatRecordSend): string => {
  try {
    switch (record.text_type) {
      case 1: {
        const parsed = JSON.parse(record.raw);
        return parsed.text ?? record.raw;
      }
      case 2:
        return "[图片]";
      case 3: {
        // 移动端发送文件时 raw 是本地路径；落库后可能为 JSON
        try {
          const parsed = JSON.parse(record.raw);
          return parsed.file_name ?? "[文件]";
        } catch {
          const name = record.raw.split(/[/\\]/).pop();
          return name || "[文件]";
        }
      }
      default:
        return record.raw;
    }
  } catch {
    return record.raw;
  }
};

const sendingList = computed(() =>
  pendingList.value.filter((r) => r.send_status === 0 || r.send_status === 1)
);
const failedList = computed(() =>
  pendingList.value.filter((r) => r.send_status === 2)
);

// 可见性控制：避免对纯待发送列表过于敏感。
// 只有待发送（排队/发送中）记录时，需等重试次数超过 1 次才显示；
// 一旦出现明确失败记录则立即显示。
const shouldShow = computed(
  () =>
    failedList.value.length > 0 ||
    sendingList.value.some((r) => r.retry_count > 1)
);

/** 统一的操作入口：置位 actingId → 执行 → 解禁；异常/超时兜底保证界面不卡死 */
const runAction = async (sendId: string, action: () => Promise<void>) => {
  actingId.value = sendId;
  clearTimeout(actingTimer);
  // 兜底：15 秒后无论 invoke 是否返回都强制解禁（正常路径后端 10 秒锁超时会返回错误）
  actingTimer = setTimeout(() => {
    actingId.value = "";
  }, 15000);
  try {
    await action();
  } finally {
    clearTimeout(actingTimer);
    actingId.value = "";
  }
};

const fetchList = async (): Promise<ChatRecordSend[]> => {
  try {
    const list = (await invoke("get_pending_send_records", {
      recvUser: props.friendUuid,
    })) as ChatRecordSend[];
    pendingList.value = list;
    return list;
  } catch (e) {
    console.error("获取待发送记录失败:", e);
    return [];
  }
};

watch(
  () => props.refreshSignal,
  () => {
    fetchList();
  }
);

// 队列未清空时每 1s 轮询一次，直到记录全部消失（发送完成/忽略/清空）
watch(pendingList, (list) => {
  clearInterval(pollTimer);
  if (list.length > 0) {
    pollTimer = setInterval(() => {
      fetchList();
    }, 1000);
  }
});

const handleRetry = (sendId: string) =>
  runAction(sendId, async () => {
    try {
      await invoke("retry_send_msg", { sendId });
      const list = await fetchList();
      const stillFailed = list.some(
        (r) => r.send_id === sendId && r.send_status === 2
      );
      if (stillFailed) {
        showToast({ message: "重发失败", icon: "fail" });
      }
    } catch (e) {
      console.error("重发失败:", e);
      showToast({ message: "重发失败", icon: "fail" });
      await fetchList();
    }
  });

const handleIgnore = (sendId: string) =>
  runAction(sendId, async () => {
    try {
      await invoke("ignore_send_msg", { sendId });
      await fetchList();
    } catch (e) {
      console.error("忽略失败:", e);
      showToast({ message: "忽略失败", icon: "fail" });
    }
  });

onMounted(() => {
  fetchList();
});

onUnmounted(() => {
  clearInterval(pollTimer);
  clearTimeout(actingTimer);
});
</script>

<template>
  <div v-if="shouldShow" class="pending-bar">
    <!-- 折叠态：窄条 + 失败计数徽标，点击整条展开 -->
    <div v-if="collapsed" class="collapsed-bar" @click="collapsed = false">
      <span class="collapsed-info">
        <span class="collapsed-dot" />
        <span>待发送记录</span>
        <span v-if="failedList.length > 0" class="collapsed-badge">
          {{ failedList.length }}
        </span>
      </span>
      <svg class="collapse-arrow" viewBox="0 0 24 24" fill="currentColor">
        <path d="M12 8l6 6 1.4-1.4L12 5.2 4.6 12.6 6 14z" />
      </svg>
    </div>

    <!-- 展开态 -->
    <div v-else class="expanded-bar">
      <div class="pane-title bar-header" @click="collapsed = true">
        <span class="header-text">发送状态</span>
        <svg class="collapse-arrow down" viewBox="0 0 24 24" fill="currentColor">
          <path d="M12 16l-6-6-1.4 1.4L12 18.8l7.4-7.4L18 10z" />
        </svg>
      </div>

      <!-- 发送中 / 排队中 -->
      <div v-if="sendingList.length > 0" class="pane">
        <div class="pane-title">发送中</div>
        <div
          v-for="record in sendingList"
          :key="record.send_id"
          class="item sending-item"
        >
          <span v-if="record.send_status === 1" class="loading-spinner" />
          <span v-else class="queued-label">排队中</span>
          <span class="item-text" :title="formatRaw(record)">
            {{ formatRaw(record) }}
          </span>
        </div>
      </div>

      <!-- 发送失败 -->
      <div v-if="failedList.length > 0" class="pane pane-failed">
        <div class="pane-title">发送失败</div>
        <div
          v-for="record in failedList"
          :key="record.send_id"
          class="item failed-item"
          :class="{ acting: actingId === record.send_id }"
        >
          <span class="item-text" :title="formatRaw(record)">
            {{ formatRaw(record) }}
          </span>
          <button
            class="action-btn resend-btn"
            :disabled="actingId === record.send_id"
            @click="handleRetry(record.send_id)"
          >
            <span class="action-icon" :class="{ spin: actingId === record.send_id }">
              <svg viewBox="0 0 24 24" fill="currentColor">
                <path
                  d="M12 6v3l4-4-4-4v3c-4.42 0-8 3.58-8 8 0 1.57.46 3.03 1.24 4.26L6.7 14.8c-.45-.83-.7-1.79-.7-2.8 0-3.31 2.69-6 6-6zm6.76 1.74L17.3 9.2c.44.84.7 1.79.7 2.8 0 3.31-2.69 6-6 6v-3l-4 4 4 4v-3c4.42 0 8-3.58 8-8 0-1.57-.46-3.03-1.24-4.26z"
                />
              </svg>
            </span>
          </button>
          <button
            class="action-btn ignore-btn"
            :disabled="actingId === record.send_id"
            @click="handleIgnore(record.send_id)"
          >
            <span class="action-icon">
              <svg viewBox="0 0 24 24" fill="currentColor">
                <path d="M19 6.4L17.6 5 12 10.6 6.4 5 5 6.4 10.6 12 5 17.6 6.4 19 12 13.4 17.6 19 19 17.6 13.4 12z" />
              </svg>
            </span>
          </button>
        </div>
      </div>
    </div>
  </div>
</template>

<style scoped lang="less">
.pending-bar {
  flex-shrink: 0;
  margin: 8px 10px;
}

.collapsed-bar {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 8px;
  padding: 8px 14px;
  background: var(--header-bg);
  backdrop-filter: blur(20px);
  border: 1px solid var(--border-light);
  border-radius: var(--radius-md);
  box-shadow: var(--shadow-sm);
  cursor: pointer;
  .collapsed-info {
    display: flex;
    align-items: center;
    gap: 8px;
    font-size: 13px;
    color: var(--text-primary);
  }
  .collapsed-dot {
    width: 8px;
    height: 8px;
    border-radius: 50%;
    background: var(--color-error);
    box-shadow: 0 0 6px rgba(255, 77, 79, 0.5);
  }
  .collapsed-badge {
    display: inline-flex;
    align-items: center;
    justify-content: center;
    min-width: 18px;
    height: 18px;
    padding: 0 5px;
    border-radius: var(--radius-full);
    background: var(--badge-bg, #ef4444);
    color: var(--badge-text, #fff);
    font-size: 11px;
    font-weight: 600;
  }
  .collapse-arrow {
    width: 16px;
    height: 16px;
    color: var(--text-tertiary);
  }
}

.expanded-bar {
  background: var(--header-bg);
  backdrop-filter: blur(20px);
  border: 1px solid var(--border-light);
  border-radius: var(--radius-md);
  box-shadow: var(--shadow-sm);
  max-height: 40vh;
  overflow-y: auto;
  -webkit-overflow-scrolling: touch;
  padding: 6px 0;
}

.bar-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  cursor: pointer;
  padding: 6px 14px;
  .header-text {
    font-size: 13px;
    font-weight: 600;
    color: var(--text-primary);
  }
  .collapse-arrow {
    width: 16px;
    height: 16px;
    color: var(--text-tertiary);
    &.down {
      transform: rotate(180deg);
    }
  }
}

.pane {
  padding: 4px 0 6px;
}
.pane-failed + .pane-failed {
  border-top: 0;
}
.pane-title {
  padding: 4px 14px;
  font-size: 12px;
  color: var(--text-tertiary);
}

.item {
  display: flex;
  align-items: center;
  gap: 8px;
  padding: 6px 14px;
  &.acting {
    opacity: 0.7;
  }
  .item-text {
    flex: 1;
    min-width: 0;
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
    font-size: 14px;
    color: var(--text-primary);
  }
}

.sending-item {
  .queued-label {
    flex-shrink: 0;
    font-size: 11px;
    color: var(--text-placeholder);
  }
  .item-text {
    color: var(--text-secondary);
  }
}

.failed-item {
  .item-text {
    color: var(--color-error);
  }
}

.loading-spinner {
  width: 14px;
  height: 14px;
  flex-shrink: 0;
  border: 2px solid var(--border-medium);
  border-top-color: var(--brand-blue);
  border-radius: 50%;
  animation: spin 0.8s linear infinite;
}

.action-btn {
  width: 28px;
  height: 28px;
  flex-shrink: 0;
  display: flex;
  align-items: center;
  justify-content: center;
  background: var(--surface);
  border: 1px solid var(--border-medium);
  border-radius: 50%;
  color: var(--text-tertiary);
  cursor: pointer;
  box-shadow: var(--shadow-xs);
  &:disabled {
    opacity: 0.5;
    cursor: not-allowed;
  }
  &:active:not(:disabled) {
    background: var(--surface-hover);
  }
  .action-icon {
    width: 15px;
    height: 15px;
    display: flex;
    align-items: center;
    justify-content: center;
    svg {
      width: 100%;
      height: 100%;
    }
    &.spin {
      animation: spin 0.8s linear infinite;
    }
  }
}

.resend-btn {
  color: var(--brand-blue);
}
.ignore-btn {
  color: var(--text-tertiary);
}

@keyframes spin {
  to {
    transform: rotate(360deg);
  }
}
</style>
