// apps/mobile/src/pages/Settings/BlackList.vue
<script setup lang="ts">
import { onMounted, ref } from "vue";
import { useRouter } from "vue-router";
import { showDialog, showToast } from "vant";
import { useAvatar } from "@/hooks/useAvatar";
import { DEFAULT_AVATAR } from "@/stores/user";
import {
  block_friend,
  get_black_list,
  search_user_by_account,
  unblock_friend,
  isBackendSuccess,
} from "@workspace/services";
import type { BlackListVo, RustResponse, UserInfo } from "@workspace/types";

interface BlackItem extends BlackListVo {
  avatarUrl: string;
}

const router = useRouter();
const { getAvatarUrl } = useAvatar();

const list = ref<BlackItem[]>([]);
const loading = ref(false);

const searchKey = ref("");
const searching = ref(false);
const searchResult = ref<UserInfo | null>(null);
const searchAvatar = ref("");
const blockLoading = ref(false);

const parseUser = (res: RustResponse): UserInfo | null => {
  if (!res.netSuccess) {
    throw new Error(res.error || "网络请求失败");
  }
  const data = JSON.parse(res.res.body);
  if (isBackendSuccess(data.code) && data.data) {
    return data.data as UserInfo;
  }
  throw new Error(data.message || "请求失败");
};

const loadList = async () => {
  loading.value = true;
  try {
    const result = await get_black_list();
    const items = await Promise.all(
      (result || []).map(async (item) => {
        const avatarUrl = item.icon ? ((await getAvatarUrl(item.icon)) || "") : "";
        return { ...item, avatarUrl };
      })
    );
    list.value = items;
  } catch (error) {
    console.error("获取黑名单失败:", error);
    showToast({ message: "获取黑名单失败", icon: "fail" });
  } finally {
    loading.value = false;
  }
};

onMounted(() => {
  loadList();
});

const goBack = () => router.back();

const onSearch = async () => {
  const key = searchKey.value.trim();
  if (!key) {
    showToast({ message: "请输入要拉黑的人的账号", icon: "none" });
    return;
  }
  searching.value = true;
  searchResult.value = null;
  searchAvatar.value = "";
  try {
    const res = await search_user_by_account(key);
    const user = parseUser(res);
    if (user?.uuid) {
      searchResult.value = user;
      searchAvatar.value = user.icon ? ((await getAvatarUrl(user.icon)) || "") : "";
    } else {
      showToast({ message: "未找到该用户", icon: "none" });
    }
  } catch (error) {
    console.error("搜索用户失败:", error);
    showToast({ message: "未找到该用户", icon: "none" });
  } finally {
    searching.value = false;
  }
};

const confirmBlock = () => {
  const user = searchResult.value;
  if (!user?.uuid) return;
  showDialog({
    title: "拉黑用户",
    message: `确定要拉黑 ${user.username || user.account || "该用户"} 吗？拉黑后将不再接收其消息。`,
    confirmButtonText: "拉黑",
    confirmButtonColor: "#ef4444",
    cancelButtonText: "取消",
  })
    .then(async () => {
      blockLoading.value = true;
      try {
        await block_friend(user.uuid);
        showToast({ message: "已拉黑", icon: "success" });
        searchKey.value = "";
        searchResult.value = null;
        searchAvatar.value = "";
        loadList();
      } catch (error) {
        console.error("拉黑失败:", error);
        showToast({ message: "拉黑失败", icon: "fail" });
      } finally {
        blockLoading.value = false;
      }
    })
    .catch(() => {});
};

const confirmUnblock = (item: BlackItem) => {
  showDialog({
    title: "移出黑名单",
    message: `确定将 ${item.username || item.account || "该用户"} 移出黑名单吗？`,
    confirmButtonText: "移出",
    cancelButtonText: "取消",
  })
    .then(async () => {
      try {
        await unblock_friend(item.uuid);
        showToast({ message: "已移出", icon: "success" });
        loadList();
      } catch (error) {
        console.error("移出黑名单失败:", error);
        showToast({ message: "移出失败", icon: "fail" });
      }
    })
    .catch(() => {});
};
</script>

<template>
  <div class="settings-page">
    <van-nav-bar title="黑名单" left-arrow @click-left="goBack" />

    <div class="search-box">
      <input
        v-model="searchKey"
        type="text"
        placeholder="输入对方账号，拉黑后无法收到其消息"
        class="search-input"
        @keyup.enter="onSearch"
      />
      <button class="search-btn" :disabled="searching" @click="onSearch">
        {{ searching ? "搜索中" : "搜索" }}
      </button>
    </div>

    <div v-if="searchResult" class="section-card">
      <div class="black-item">
        <img
          class="black-avatar"
          :src="searchAvatar || DEFAULT_AVATAR"
          alt="avatar"
          @error="($event.target as HTMLImageElement).src = DEFAULT_AVATAR"
        />
        <div class="black-info">
          <div class="black-name">
            {{ searchResult.username || "-" }}
            <UserTypeTag :type="searchResult.user_type" />
          </div>
          <div class="black-account">{{ searchResult.account || "-" }}</div>
        </div>
        <button class="btn-danger" :disabled="blockLoading" @click="confirmBlock">
          {{ blockLoading ? "拉黑中" : "拉黑" }}
        </button>
      </div>
    </div>

    <div class="section-card">
      <div class="card-header">
        <span class="header-title">已拉黑（{{ list.length }}）</span>
      </div>
      <div v-if="loading" class="list-state">加载中...</div>
      <div v-else-if="list.length === 0" class="list-state empty-state">
        黑名单为空，被拉黑的人将无法再向你发送消息
      </div>
      <div v-else>
        <div v-for="item in list" :key="item.uuid" class="black-item">
          <img
            class="black-avatar"
            :src="item.avatarUrl || DEFAULT_AVATAR"
            alt="avatar"
            @error="($event.target as HTMLImageElement).src = DEFAULT_AVATAR"
          />
          <div class="black-info">
            <div class="black-name">
              {{ item.username || "-" }}
              <UserTypeTag :type="item.user_type" />
            </div>
            <div class="black-account">{{ item.account || "-" }}</div>
          </div>
          <button class="btn-plain" @click="confirmUnblock(item)">移出</button>
        </div>
      </div>
    </div>
  </div>
</template>

<style scoped lang="less">
.settings-page {
  min-height: 100vh;
  background: var(--page-bg);
  padding-bottom: 40px;

  :deep(.van-nav-bar) {
    position: sticky;
    top: 0;
    z-index: 100;
  }
}

.search-box {
  display: flex;
  gap: 8px;
  margin: 16px 16px 0;
}

.search-input {
  flex: 1;
  min-width: 0;
  height: 42px;
  padding: 0 14px;
  background: var(--input-bg);
  border: 1px solid var(--input-border);
  border-radius: var(--radius-sm);
  color: var(--text-primary);
  font-size: 14px;
  outline: none;
  transition: border-color var(--transition-fast);

  &:focus {
    border-color: var(--input-border-focus);
  }

  &::placeholder {
    color: var(--text-placeholder);
  }
}

.search-btn {
  height: 42px;
  padding: 0 20px;
  background: var(--gradient-primary);
  border: none;
  border-radius: var(--radius-sm);
  color: var(--text-inverse);
  font-size: 14px;
  font-weight: 500;
  cursor: pointer;
  transition: all var(--transition-fast);

  &:disabled {
    opacity: 0.6;
  }
}

.section-card {
  margin: 16px 16px 0;
  background: var(--surface);
  border: 1px solid var(--border-light);
  border-radius: var(--radius-lg);
  overflow: hidden;
  box-shadow: var(--shadow-xs);
}

.card-header {
  padding: 14px 16px 6px;
}

.header-title {
  font-size: 14px;
  font-weight: 600;
  color: var(--text-primary);
}

.list-state {
  padding: 28px 16px;
  text-align: center;
  font-size: 13px;
  color: var(--text-tertiary);
}

.empty-state {
  padding: 32px 16px;
  color: var(--text-placeholder);
}

.black-item {
  display: flex;
  align-items: center;
  gap: 14px;
  padding: 14px 16px;
  border-bottom: 1px solid var(--border-light);

  &:last-child {
    border-bottom: none;
  }
}

.black-avatar {
  width: 44px;
  height: 44px;
  border-radius: 50%;
  object-fit: cover;
  flex-shrink: 0;
  background: var(--surface-alt);
}

.black-info {
  flex: 1;
  min-width: 0;
}

.black-name {
  font-size: 15px;
  font-weight: 500;
  color: var(--text-primary);
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}

.black-account {
  margin-top: 2px;
  font-size: 12px;
  color: var(--text-tertiary);
}

.btn-danger {
  flex-shrink: 0;
  height: 32px;
  padding: 0 16px;
  background: rgba(239, 68, 68, 0.08);
  border: 1px solid rgba(239, 68, 68, 0.25);
  border-radius: var(--radius-sm);
  color: #ef4444;
  font-size: 13px;
  cursor: pointer;

  &:disabled {
    opacity: 0.6;
  }

  &:active {
    background: rgba(239, 68, 68, 0.15);
  }
}

.btn-plain {
  flex-shrink: 0;
  height: 32px;
  padding: 0 16px;
  background: var(--surface-alt);
  border: 1px solid var(--border-medium);
  border-radius: var(--radius-sm);
  color: var(--text-secondary);
  font-size: 13px;
  cursor: pointer;

  &:active {
    background: var(--surface-active);
  }
}
</style>

// apps/pc/src/pages/Home/Settings/components/BlackList.tsx
import UserTypeTag from '@/components/UserTypeTag';
import { DEFAULT_ICON } from '@/constants';
import { useIntl } from '@umijs/max';
import {
  block_friend,
  get_black_list,
  getFiles,
  search_user_by_account,
  unblock_friend,
  isHttpSuccess,
} from '@workspace/services';
import { BlackListVo, UserInfo } from '@workspace/types';
import { Button, Card, Empty, Input, Modal, Spin, Typography, message } from 'antd';
import { useEffect, useState } from 'react';
import styles from '../Settings.less';

const { Title, Text } = Typography;

const BlackList = () => {
  const intl = useIntl();
  const [list, setList] = useState<BlackListVo[]>([]);
  const [avatarMap, setAvatarMap] = useState<Map<string, string>>(new Map());
  const [loading, setLoading] = useState(false);

  const [searchKey, setSearchKey] = useState('');
  const [searching, setSearching] = useState(false);
  const [searchResult, setSearchResult] = useState<UserInfo | null>(null);
  const [searchAvatar, setSearchAvatar] = useState('');
  const [blockConfirmVisible, setBlockConfirmVisible] = useState(false);
  const [blockLoading, setBlockLoading] = useState(false);

  const loadList = async () => {
    setLoading(true);
    try {
      const result = await get_black_list();
      const blackList = result || [];
      setList(blackList);

      const avatarMap = new Map<string, string>();
      for (const item of blackList) {
        if (item.icon) {
          try {
            const files = await getFiles(item.icon);
            if (files?.[0]?.tauri_file_path) {
              avatarMap.set(item.uuid, files[0].tauri_file_path);
            }
          } catch (error) {
            console.log(error);
          }
        }
      }
      setAvatarMap(avatarMap);
    } catch (error) {
      console.error('获取黑名单失败:', error);
      message.error(intl.formatMessage({ id: 'settings.blacklist.loadFailed' }));
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    loadList();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const getUserIcon = async (icon: string): Promise<string> => {
    try {
      const files = await getFiles(icon);
      return files?.[0]?.tauri_file_path || '';
    } catch (error) {
      console.error('获取头像失败:', error);
      return '';
    }
  };

  const handleSearch = async () => {
    if (!searchKey.trim()) return;
    setSearching(true);
    try {
      const result = await search_user_by_account(searchKey.trim());
      if (result.netSuccess && isHttpSuccess(result.res.status)) {
        const data = JSON.parse(result.res.body);
        const user: UserInfo = data.data;
        if (user?.uuid) {
          setSearchResult(user);
          setSearchAvatar(await getUserIcon(user.icon || ''));
        } else {
          setSearchResult(null);
          message.info(intl.formatMessage({ id: 'settings.blacklist.notFound' }));
        }
      } else {
        message.error(intl.formatMessage({ id: 'settings.blacklist.notFound' }));
      }
    } catch (error) {
      console.error('搜索用户失败:', error);
      message.error(intl.formatMessage({ id: 'settings.blacklist.notFound' }));
    } finally {
      setSearching(false);
    }
  };

  const handleBlock = async () => {
    if (!searchResult?.uuid) return;
    setBlockLoading(true);
    try {
      await block_friend(searchResult.uuid);
      message.success(intl.formatMessage({ id: 'settings.blacklist.blockSuccess' }));
      setBlockConfirmVisible(false);
      setSearchResult(null);
      setSearchKey('');
      setSearchAvatar('');
      loadList();
    } catch (error) {
      console.error('拉黑失败:', error);
      message.error(intl.formatMessage({ id: 'settings.blacklist.blockFailed' }));
    } finally {
      setBlockLoading(false);
    }
  };

  const handleUnblock = async (uuid: string) => {
    try {
      await unblock_friend(uuid);
      message.success(intl.formatMessage({ id: 'settings.blacklist.unblockSuccess' }));
      loadList();
    } catch (error) {
      console.error('取消拉黑失败:', error);
      message.error(intl.formatMessage({ id: 'settings.blacklist.unblockFailed' }));
    }
  };

  const cancelText = intl.formatMessage({ id: 'settings.blacklist.cancel' });
  const blockText = intl.formatMessage({ id: 'settings.blacklist.block' });

  return (
    <div className={styles.settingSection}>
      <Title level={3} className={styles.sectionTitle}>
        {intl.formatMessage({ id: 'settings.blacklist.title' })}
      </Title>

      <Card className={styles.settingCard}>
        <div className={styles.blacklistSearch}>
          <Input
            placeholder={intl.formatMessage({
              id: 'settings.blacklist.searchPlaceholder',
            })}
            value={searchKey}
            allowClear
            onChange={(e) => setSearchKey(e.target.value)}
            onPressEnter={handleSearch}
            suffix={
              <Button type="primary" size="small" loading={searching} onClick={handleSearch}>
                {intl.formatMessage({ id: 'settings.blacklist.search' })}
              </Button>
            }
          />
        </div>

        {searchResult && (
          <div className={styles.blacklistItem}>
            <img
              className={styles.blacklistAvatar}
              src={searchAvatar || DEFAULT_ICON}
              alt="avatar"
              onError={(e) => {
                (e.target as HTMLImageElement).src = DEFAULT_ICON;
              }}
            />
            <div className={styles.blacklistIdentity}>
              <Text className={styles.blacklistName}>
                {searchResult.username || '-'}
                <UserTypeTag type={searchResult.user_type} />
              </Text>
              <Text type="secondary" className={styles.blacklistAccount}>
                {searchResult.account || '-'}
              </Text>
            </div>
            <Button size="small" danger onClick={() => setBlockConfirmVisible(true)}>
              {blockText}
            </Button>
          </div>
        )}

        <Spin spinning={loading}>
          {list.length === 0 ? (
            <Empty description={intl.formatMessage({ id: 'settings.blacklist.empty' })} />
          ) : (
            list.map((item) => (
              <div key={item.uuid} className={styles.blacklistItem}>
                <img
                  className={styles.blacklistAvatar}
                  src={avatarMap.get(item.uuid) || DEFAULT_ICON}
                  alt="avatar"
                  onError={(e) => {
                    (e.target as HTMLImageElement).src = DEFAULT_ICON;
                  }}
                />
                <div className={styles.blacklistIdentity}>
                  <Text className={styles.blacklistName}>
                    {item.username || '-'}
                    <UserTypeTag type={item.user_type} />
                  </Text>
                  <Text type="secondary" className={styles.blacklistAccount}>
                    {item.account || '-'}
                  </Text>
                </div>
                <Button size="small" onClick={() => handleUnblock(item.uuid)}>
                  {intl.formatMessage({ id: 'settings.blacklist.unblock' })}
                </Button>
              </div>
            ))
          )}
        </Spin>
      </Card>

      <Modal
        title={intl.formatMessage({ id: 'settings.blacklist.blockConfirmTitle' })}
        open={blockConfirmVisible}
        onOk={handleBlock}
        onCancel={() => setBlockConfirmVisible(false)}
        okText={blockText}
        cancelText={cancelText}
        okButtonProps={{ danger: true, loading: blockLoading }}
      >
        {searchResult && (
          <p>
            {intl.formatMessage(
              { id: 'settings.blacklist.blockConfirmMsg' },
              { name: searchResult.username || searchResult.account },
            )}
          </p>
        )}
      </Modal>
    </div>
  );
};

export default BlackList;
